Repository ak-0283/Coding_Club, pull requests merged in 2025-02, with the labels that each got.

#12 Added dark mode toggle button with emoji
  Frontend/index.html
  Frontend/script.js
  Frontend/style.css
Labels: JWOC, Hard

#9 enhanced footer
  Frontend/index.html
  Frontend/script.js
  Frontend/style.css
Labels: JWOC, Medium

#21 Added greeting feature
  Frontend/index.html
  Frontend/script.js
  Frontend/style.css
Labels: JWOC, Easy

#23 Added greeting alert feature on page load
  Frontend/index.html
  Frontend/script.js
  Frontend/style.css
Labels: JWOC, Medium

#32 Registration pages done
  Frontend/index.html
  Frontend/login.css
  Frontend/login.html
  Frontend/script.js
  Frontend/signup.css
  Frontend/signup.html
  Frontend/style.css
  Frontend/toggle.css
  Frontend/toggle.js
Labels: JWOC, Hard

#35 Feedback form added
  Frontend/feedback.html
  Frontend/index.html
Labels: JWOC, Medium

#38 Added typing effect on Navbar title (Coding Club)
  Frontend/index.html
  Frontend/script.js
  Frontend/style.css
Labels: JWOC, Medium

#18 Added Logo to the Header
  Frontend/codingclub.png
  Frontend/index.html
  Frontend/style.css
Labels: JWOC, Hard

#43 Re-added Blinking Title Effect for Navbar
  Frontend/script.js
  Frontend/style.css
  clear
Labels: JWOC, Easy, good issue

#48 fixed responsiveness in the contributor page
  Frontend/contributor.css
  Frontend/toggle.js
Labels: JWOC, Medium, good issue

#50 Improve Mobile Responsiveness for Navbar
  Frontend/index.html
  Frontend/script.js
  Frontend/style.css
Labels: JWOC 2025, Hard

#54 project image added
  Frontend/color.jpeg
  Frontend/guess.jpeg
  Frontend/index.html
  Frontend/password.jpeg
  Frontend/todo.jpeg
Labels: JWOC 2025, Medium

#56 Synchronized the colour of the sections according to the dark theme
  Frontend/event.css
  Frontend/style.css
Labels: JWOC 2025, Hard

#61 feedback page modified
  Frontend/feedback.html
  Frontend/index.html
Labels: JWOC 2025, Easy, good issue

#79 faq page added
  Frontend/contributor.html
  Frontend/index.html
Labels: JWOC 2025, Hard

#102 navbar & footer added in privacy policy page
  Frontend/privacy.html
Labels: JWOC 2025, Hard

#107 Terms page navbar added
  Frontend/privacy.html
  Frontend/terms.html
Labels: JWOC 2025, Medium

#109 Animation Home
  Frontend/index.html
Labels: JWOC 2025, Hard

#108 redirect link fixed
  Frontend/terms.html
Labels: JWOC 2025, Easy

#110 Form web3
  Frontend/index.html
  Frontend/script.js
  Frontend/terms.html
  Frontend/web3.js
Labels: JWOC 2025, Medium

#118 UI fixed
  Frontend/card.css
  Frontend/index.html
  Frontend/terms.html
Labels: JWOC 2025, Hard

#121 Fixed the width of the navbar and the footer
  Frontend/style.css
Labels: JWOC 2025, Hard

#134 Develop a Dedicated Projects Page with Images & Search Functionality
  .vscode/settings.json
  Frontend/contributor.html
  Frontend/index.html
  Frontend/project.css
  Frontend/projectpage.html
  Frontend/review.html
  Frontend/script.js
  Frontend/terms.html
Labels: JWOC 2025, Hard

#136 Feedback form
  Frontend/feedback.js
  Frontend/index.html
Labels: JWOC 2025, Hard

#144 Privacy redirect fixed
  Frontend/index.html
  Frontend/privacy.html
  Frontend/projectpage.html
Labels: JWOC 2025, Medium

#147 Made the home section responsive for all dimensions
  Frontend/style.css
Labels: JWOC 2025, Hard

#155 more event page enhanced
  Frontend/event.html
Labels: JWOC 2025, Medium

#156 Privacy policy page text color fix
  Frontend/privacy.html
  Frontend/style.css
  Frontend/terms.html
Labels: JWOC 2025, Hard

#166 fixed the title for the review page
  Frontend/review.html
Labels: JWOC 2025, Hard

#167 Fixed the footer of the project page
  Frontend/index.html
  Frontend/project.css
  Frontend/projectpage.html
  Frontend/style.css
Labels: JWOC 2025, Hard

#168 Fixed teh dark mode issue for terms and condition page
  Frontend/style.css
  Frontend/terms.html
Labels: JWOC 2025, Medium

#173 Blog
  Frontend/blog.html
  Frontend/index.html
Labels: JWOC 2025, Hard

#178 Added style to add event form and made it responsive
  Frontend/index.html
  Frontend/style.css
Labels: JWOC 2025, Hard

#179 Created the login signup backend
  Frontend/default.jpg
  Frontend/index.html
  Frontend/login.html
  Frontend/login.js
  Frontend/signup.js
Labels: JWOC 2025, Hard

#180 Added the event form in event page
  Frontend/event.css
  Frontend/event.html
Labels: JWOC 2025, Hard

#182 more project page added
  Frontend/index.html
  Frontend/projectpage.html
Labels: JWOC 2025, Medium

#184 Password generator website added
  Frontend/index.html
Labels: JWOC 2025

#185 Color generator website added
  Frontend/index.html
Labels: JWOC 2025

#202 Fixed the responsiveness of event section
  Frontend/style.css
Labels: JWOC 2025, Hard

#203 Fixed the project page
  Frontend/default.jpg
  Frontend/index.html
  Frontend/projectpage.html
Labels: JWOC 2025, Medium

#209 Fixed the title of the page
  Frontend/projectpage.html
Labels: JWOC 2025, Medium

#208 Fixed the Quick links for the contribute page
  Frontend/contributor.html
Labels: JWOC 2025, Hard

#210 Dark mode faq text visibility fixed
  Frontend/style.css
Labels: JWOC 2025, Medium

#212 Minor Ui Change
  Frontend/index.html
Labels: JWOC 2025, Hard

#213 Fixed the Terms page
  Frontend/privacy.html
  Frontend/terms.html
Labels: JWOC 2025

#229 Darkmode added in the blog page
  Frontend/blog.css
  Frontend/blog.html
  Frontend/card.css
  Frontend/contributor.js
  Frontend/privacy.html
  Frontend/projectpage.html
  Frontend/review.html
Labels: JWOC 2025

#218 project nav fixed
  Frontend/privacy.html
  Frontend/projectpage.html
Labels: JWOC 2025

#244 Fixed Website name
  Frontend/blog.html
  Frontend/contributor.html
  Frontend/index.html
  Frontend/privacy.html
  Frontend/projectpage.html
  Frontend/review.html
  Frontend/terms.html
Labels: JWOC 2025, Medium

#264 Logout feature added
  Frontend/blog.html
  Frontend/index.html
Labels: JWOC 2025, Hard

#261 events link footer now redirect to main page event section
  Frontend/index.html
Labels: JWOC 2025, Easy

#262 search bar with filter added in project section
  Frontend/index.html
Labels: JWOC 2025

#220 navbar overlapping issue #157 fixed!
  Frontend/index.html
  Frontend/style.css
Labels: JWOC 2025

#259 todo website link added
  Frontend/index.html
Labels: JWOC 2025, Hard

#260 Guessing game website added.
  Frontend/index.html
Labels: JWOC 2025, Hard

#230 Weather App added
  Frontend/WeatherApp/weather.css
  Frontend/WeatherApp/weather.html
  Frontend/WeatherApp/weather.js
  Frontend/projectpage.html
Labels: JWOC 2025

#266 leaderboard added for past 3 events
  Frontend/event.html
  Frontend/leaderboard.html
  Frontend/leaderboard1.html
  Frontend/leaderboard2.html
Labels: JWOC 2025, Hard

#248 Fixed Overflow Bug- footer of privacy page
  Frontend/privacy.html
Labels: JWOC 2025, Hard

#282 Fixed the alignment and responsiveness of footer in event page
  Frontend/event.html
  Frontend/style.css
Labels: JWOC 2025, Hard

#292 Added logo
  Frontend/codingclub.png
Labels: JWOC 2025, Hard

#270 issue #158 dark mode fix in events page
  Frontend/index.html
Labels: JWOC 2025, Medium

#297 Fixed the width of navbar
  Frontend/style.css
Labels: JWOC 2025, Hard

#269 no search result added in event search bar
  Frontend/index.html
Labels: JWOC 2025, Medium

#274 About us page expanded
  Frontend/index.html
Labels: JWOC 2025, Medium

#275 Faq search bar updated with "no results found"
  Frontend/index.html
Labels: JWOC 2025, Hard

#276 Subscribe button responsiveness added
  Frontend/style.css
Labels: JWOC 2025, Hard

#277 toggle eye implemented in sign up form.
  Frontend/signup.css
  Frontend/signup.html
  Frontend/signup.js
Labels: JWOC 2025, Easy

#278 eye added in login page
  Frontend/login.css
  Frontend/login.html
  Frontend/login.js
Labels: JWOC 2025, Easy

#280 Contributor page "no result found" added
  Frontend/contributor.js
  Frontend/index.html
Labels: JWOC 2025, Medium

#286 quiz app added in view demo button
  Frontend/projectpage.html
  Frontend/quiz.html
Labels: JWOC 2025, Hard

#287 Drum kit website added
  Frontend/projectpage.html
Labels: JWOC 2025, Hard

#288 Dictionary website added
  Frontend/projectpage.html
Labels: JWOC 2025, Hard

#289 Portfolio website added
  Frontend/projectpage.html
Labels: JWOC 2025

#291 Redirecting Icon fixed
  Frontend/components/github.png
  Frontend/components/linkidn.png
  Frontend/index.html
Labels: JWOC 2025, Medium

#301 Fixed the footer
  Frontend/style.css
Labels: JWOC 2025, Hard

#318 Bug footer of terms Page
  Frontend/terms.html
Labels: JWOC 2025, Hard

#319 Fixed Navbar and footer of home page
  Frontend/index.html
  Frontend/style.css
Labels: JWOC 2025, Hard

#309 Bug fix welcome user tag
  Frontend/index.html
  Frontend/style.css
Labels: JWOC 2025

#320 Fixed Navbar and footer of blog page
  Frontend/blog.html
  Frontend/style.css
Labels: JWOC 2025, Hard

#324 Fixed Navbar and Footer of more event page
  Frontend/event.html
  Frontend/index.html
  Frontend/style.css
Labels: JWOC 2025, Medium

#346 Added social icons in contact form
  Frontend/download.jpg
  Frontend/download.png
  Frontend/index.html
Labels: JWOC 2025, Medium

#334 Added logo
  Frontend/index.html
Labels: JWOC 2025

#325 Fixed Navbar of More Project page
  Frontend/projectpage.html
Labels: JWOC 2025, Medium

#326 Bug navbar of privacy
  Frontend/privacy.html
Labels: JWOC 2025, Hard

#348 Made the contact page responsive
  Frontend/style.css
Labels: JWOC 2025, Hard

#349 Fixed the image of about section
  Frontend/index.html
  Frontend/style.css
Labels: JWOC 2025, Hard

#359 added footer links in the terms page
  Frontend/about.css
  Frontend/blog.css
  Frontend/contributor.css
  Frontend/contributor.html
  Frontend/event.css
  Frontend/event.html
  Frontend/index.html
  Frontend/project.css
  Frontend/projectpage.html
  Frontend/review.html
  Frontend/terms.html
Labels: JWOC 2025, Medium

#327 Redirect urls added in the project page
  Frontend/event.js
Labels: JWOC 2025, Medium

#335 Made changes the title of the faq, feedback ,about
  Frontend/style.css
Labels: JWOC 2025, Hard

#364 Added icons in the social links (issue #350)
  Frontend/contributor.html
  Frontend/index.html
  Frontend/projectpage.html
  Frontend/review.html
  Frontend/style.css
Labels: JWOC 2025, Medium

#367 Correct links
  Frontend/AllLoginPage/loginPage/login.html
  Frontend/WeatherApp/weather.html
  Frontend/blogPage/blog.html
  Frontend/contributorPage/contributor.html
  Frontend/eventPage/event.html
  Frontend/images/github.png
  Frontend/mainPage/index.html
  Frontend/privacyPage/privacy.html
  Frontend/projectPage/projectpage.html
  Frontend/reviewPage/review.html
  Frontend/signupPage/signup.html
  Frontend/termsPage/terms.html
Labels: JWOC 2025, Medium

#369 404 fixed file rendering
  Frontend/AllLoginPage/ailoginPage/ailogin.html
  Frontend/AllLoginPage/beginloginPage/beginlogin.html
  Frontend/AllLoginPage/loginPage/login.html
  Frontend/AllLoginPage/stackloginPage/stacklogin.html
  Frontend/blogPage/blog.html
  Frontend/contributorPage/contributor.html
  Frontend/eventPage/event.html
  Frontend/index.html
  Frontend/privacyPage/privacy.html
  Frontend/projectPage/projectpage.html
  Frontend/reviewPage/review.html
  Frontend/signupPage/signup.html
  Frontend/termsPage/terms.html
Labels: JWOC 2025, Hard

#370 Added Why Choose Us
  Frontend/index.html
  Frontend/mainPage/style.css
Labels: JWOC 2025, Hard

#373 Fixed the about section in dark mode
  Frontend/mainPage/style.css
Labels: JWOC 2025, Medium

#339 added back button in weather app
  Frontend/WeatherApp/weather.css
  Frontend/WeatherApp/weather.html
Labels: JWOC 2025, Medium

#376 Added footer to the signup page
  Frontend/signupPage/signup.css
  Frontend/signupPage/signup.html
Labels: JWOC 2025, Hard

#387 Weather app styles added
  Frontend/User/user.html
  Frontend/WeatherApp/weather.css
  Frontend/contributorPage/contributor.html
  Frontend/eventPage/event.html
  Frontend/index.html
  Frontend/privacyPage/privacy.html
  Frontend/projectPage/projectpage.html
  Frontend/reviewPage/review.html
Labels: JWOC 2025, Hard

#393 Fix the response issue in review page after 768px
  Frontend/reviewPage/review.css
  Frontend/reviewPage/review.html
Labels: JWOC 2025, Hard

#394 Fixed 404 bug
  Frontend/signupPage/signup.html
Labels: JWOC 2025, Easy

#388 Api for quiz added
  Frontend/quiz/quiz.html
  Frontend/quiz/quiz.json
Labels: JWOC 2025

#395 Design Footer
  Frontend/signupPage/signup.css
  Frontend/signupPage/signup.html
Labels: JWOC 2025, Hard

#396 stopwatch added
  Frontend/projectPage/projectpage.html
  Frontend/stopWatch/stopwatch.css
  Frontend/stopWatch/stopwatch.html
  Frontend/stopWatch/stopwatch.js
Labels: JWOC 2025, Medium

#400 Added margin
  Frontend/AllLoginPage/loginPage/login.css
Labels: JWOC 2025, Medium

#402 Added Validate phone input
  Frontend/signupPage/signup.css
  Frontend/signupPage/signup.html
Labels: JWOC 2025, Medium

#403 Fix the alignment of the contributors card in large screen
  Frontend/contributorPage/contributor.css
Labels: JWOC 2025, Hard

#404 Fixed Placeholder's size
  Frontend/AllLoginPage/loginPage/login.css
Labels: JWOC 2025, Medium

#418 Redesigned ui of privacy page
  Frontend/privacyPage/privacy.css
  Frontend/privacyPage/privacy.html
Labels: JWOC 2025, Hard

#406 resources page added
  Frontend/index.html
  Frontend/resource/resource.css
  Frontend/resource/resource.html
Labels: JWOC 2025, Hard

#407 More event page header ,footer modified with typing text, greeting card, dark mode functionality
  Frontend/eventPage/event.html
Labels: JWOC 2025, Hard

#408 Logo added in more event page
  Frontend/mainPage/style.css
Labels: JWOC 2025, Medium

#413 Project search bar modified with "no search results"
  Frontend/index.html
Labels: JWOC 2025, Medium

#414 Contributor page footer modified with all links
  Frontend/contributorPage/contributor.html
Labels: JWOC 2025, Medium

#417 project level Section added
  Frontend/projectPage/projectpage.html
Labels: JWOC 2025, Hard
