Repository ak-0283/Coding_Club, pull requests merged in 2025-03, with the labels that each got.

#437 blog page navbar modified
  Frontend/index.html
Labels: JWOC 2025, Medium

#442 Projects section search bar modified with "no results found"
  Frontend/index.html
Labels: JWOC 2025, Hard

#443 Privacy and terms page logo fixed
  Frontend/images/codingclub.svg
  Frontend/privacyPage/privacy.html
  Frontend/termsPage/terms.html
Labels: JWOC 2025, Medium

#446 navbar & footer added in all Leaderboard pages
  Frontend/eventPage/event.html
  Frontend/leaderboard/leaderboard.html
  Frontend/leaderboard/leaderboard1.html
  Frontend/leaderboard/leaderboard2.html
Labels: JWOC 2025, Hard

#447 Scroll to top button added in all leaderboard pages
  Frontend/leaderboard/leaderboard.html
  Frontend/leaderboard/leaderboard1.html
  Frontend/leaderboard/leaderboard2.html
Labels: JWOC 2025, Medium

#449 Loading animation
  Frontend/image1.jpeg
  Frontend/image2.jpeg
  Frontend/image3.avif
  Frontend/index.html
  Frontend/infinite-spinner.svg
  Frontend/mainPage/style.css
  Frontend/profile.png
Labels: JWOC 2025, Hard

#432 Updated UI of terms
  Frontend/termsPage/terms.css
  Frontend/termsPage/terms.html
Labels: JWOC 2025, Medium

#472 Add the currency converter app
  Frontend/.gitignore
  Frontend/currencyConverter/Screenshot 02-03-2025 01_21_54.png
  Frontend/currencyConverter/back.png
  Frontend/currencyConverter/currency.css
  Frontend/currencyConverter/index.html
  Frontend/projectPage/projectpage.html
Labels: JWOC 2025, Hard

#462 Added dark mode on login page
  Frontend/AllLoginPage/loginPage/login.css
  Frontend/AllLoginPage/loginPage/login.html
Labels: JWOC 2025, Hard

#463 Added Dark mode in signup page
  Frontend/signupPage/signup.css
  Frontend/signupPage/signup.html
Labels: JWOC 2025, Hard

#464 Added custom scrollbar in signup page
  Frontend/signupPage/signup.css
Labels: JWOC 2025, Medium

#465 Fixed 404 error in login's Hackathon
  Frontend/AllLoginPage/ailoginPage/ailogin.html
Labels: JWOC 2025, Easy

#466 Added Dark mode hackathon login page
  Frontend/AllLoginPage/ailoginPage/ailogin.css
  Frontend/AllLoginPage/ailoginPage/ailogin.html
Labels: JWOC 2025, Hard

#467 Fixed 404 error of fullstack login page
  Frontend/AllLoginPage/stackloginPage/stacklogin.html
Labels: JWOC 2025, Easy

#468 Added Dark mode on fullstack login
  Frontend/AllLoginPage/stackloginPage/stacklogin.css
  Frontend/AllLoginPage/stackloginPage/stacklogin.html
Labels: JWOC 2025, Hard

#473 Added dark mode in begin hackathon login page
  Frontend/AllLoginPage/beginloginPage/beginlogin.css
  Frontend/AllLoginPage/beginloginPage/beginlogin.html
Labels: JWOC 2025, Hard

#474 Fixed design of more event button
  Frontend/eventPage/event.css
  Frontend/index.html
  Frontend/mainPage/style.css
Labels: JWOC 2025, Medium

#476 Fixed alignment of footer(main page)
  Frontend/mainPage/style.css
Labels: JWOC 2025, Hard

#477 Update login page
  Frontend/AllLoginPage/loginPage/login.css
Labels: JWOC 2025, Hard

#479 Update signup page
  Frontend/signupPage/signup.css
Labels: JWOC 2025, Hard

#419 Calculator Added
  Frontend/Calculator/calculator.css
  Frontend/Calculator/calculator.html
  Frontend/Calculator/calculator.js
  Frontend/projectPage/projectpage.html
Labels: JWOC 2025, Hard

#422 Scoreboard added
  Frontend/quiz/quiz.html
Labels: JWOC 2025, Hard

#423 time out added
  Frontend/quiz/quiz.html
Labels: JWOC 2025, Medium

#433 Expense Tracker added
  Frontend/ExpenseTracker/expenseTracker.html
  Frontend/ExpenseTracker/expenseTracker.js
  Frontend/ExpenseTracker/expensetracker.css
  Frontend/projectPage/projectpage.html
Labels: JWOC 2025, Hard

#434 Notes added
  Frontend/NotesAPP/notes.css
  Frontend/NotesAPP/notes.html
  Frontend/NotesAPP/notes.js
  Frontend/projectPage/projectpage.html
Labels: JWOC 2025, Hard

#435 Typing Speed added
  Frontend/projectPage/projectpage.html
  Frontend/typingSpeed/typingSpeed.css
  Frontend/typingSpeed/typingSpeed.html
  Frontend/typingSpeed/typingSpeed.js
Labels: JWOC 2025, Hard

#483 Made the stopwatch ui enhanced
  Frontend/stopWatch/stopwatch.css
Labels: JWOC 2025, Hard

#484 Added lap functionality
  Frontend/projectPage/projectpage.html
  Frontend/stopWatch/stopwatch.css
  Frontend/stopWatch/stopwatch.html
  Frontend/stopWatch/stopwatch.js
Labels: JWOC 2025, Medium

#485 Adding darkmode to quiz app and back btn
  Frontend/quiz/quiz.html
Labels: JWOC 2025, Medium

#488 ui improved and edit and notification added
  Frontend/Calculator/calculator.css
  Frontend/Calculator/calculator.html
  Frontend/Calculator/calculator.js
  Frontend/NotesAPP/notes.css
  Frontend/NotesAPP/notes.html
  Frontend/NotesAPP/notes.js
Labels: JWOC 2025, Hard

#490 UI IMPROVED and NUMPAD REQ ADDED
  Frontend/Calculator/calculator.css
  Frontend/Calculator/calculator.html
  Frontend/Calculator/calculator.js
  Frontend/currencyConverter/currency.css
Labels: JWOC 2025, Hard

#491 Accuracy added and personal best added
  Frontend/typingSpeed/typingSpeed.css
  Frontend/typingSpeed/typingSpeed.html
  Frontend/typingSpeed/typingSpeed.js
Labels: JWOC 2025, Medium

#492 search bar added to notes
  Frontend/NotesAPP/notes.html
  Frontend/index.html
  Frontend/mainPage/style.css
Labels: JWOC 2025, Hard

#493 Fixed Dictionary
  Frontend/Dictionary/dictionary.html
  Frontend/projectPage/projectpage.html
Labels: JWOC 2025, Medium

#494 fixed color picker
  Frontend/ColorPicker/colorpicker.html
  Frontend/drumKit/drumkit.html
  Frontend/guessing game/guessGame.html
  Frontend/index.html
  Frontend/password generator/passgen.html
Labels: JWOC 2025, Medium

#495 Fixed password generator
  Frontend/index.html
  Frontend/password generator/passgen.html
Labels: JWOC 2025, Medium

#497 fixed the todo
  Frontend/guessing game/guessGame.html
  Frontend/index.html
  Frontend/todo/todo.html
Labels: JWOC 2025, Hard

#499 FAQ fixed
  Frontend/index.html
  Frontend/projectPage/project.css
Labels: JWOC 2025, Hard

#534 Added User Profile page
  Frontend/User/user.html
  Frontend/contributorPage/contributor.html
  Frontend/eventPage/event.html
  Frontend/index.html
  Frontend/projectPage/projectpage.html
  Frontend/reviewPage/review.html
Labels: JWOC 2025, Hard

#535 Fixed Container view
  Frontend/index.html
  Frontend/mainPage/style.css
Labels: JWOC 2025, Hard

#531 search bar with filter added in all pages of leaderboard
  Frontend/leaderboard/leaderboard.html
  Frontend/leaderboard/leaderboard1.html
  Frontend/leaderboard/leaderboard2.html
Labels: JWOC 2025, Medium

#532 Leader board dark mode added in every page
  Frontend/leaderboard/leaderboard.html
  Frontend/leaderboard/leaderboard1.html
  Frontend/leaderboard/leaderboard2.html
Labels: JWOC 2025, Hard

#546 Added Validation on feedback form
  Frontend/index.html
Labels: JWOC 2025, Medium

#547 Added Dark mode on User Profile
  Frontend/User/user.html
Labels: JWOC 2025, Medium

#548 Fixed container of contributor page
  Frontend/contributorPage/contributor.css
Labels: JWOC 2025, Medium

#576 Added Dark mode on weather app
  Frontend/WeatherApp/weather.css
  Frontend/WeatherApp/weather.html
  Frontend/WeatherApp/weather.js
Labels: JWOC 2025, Medium

#577 Fixed over flow and back button(quiz app)
  Frontend/quiz/quiz.html
Labels: JWOC 2025, Hard

#578 Added Custom scrollbar and change light mode theme and added dark mode
  Frontend/Calculator/calculator.css
  Frontend/Calculator/calculator.html
  Frontend/Calculator/calculator.js
Labels: JWOC 2025, Hard

#579 Fixed bug of functionality(calculator)
  Frontend/Calculator/calculator.js
Labels: JWOC 2025, Hard

#580 Implemented Dark mode and back button
  Frontend/ExpenseTracker/expenseTracker.html
  Frontend/ExpenseTracker/expenseTracker.js
  Frontend/ExpenseTracker/expensetracker.css
Labels: JWOC 2025, Hard

#581 Implemented dark mode on currency converter
  Frontend/currencyConverter/currency.css
  Frontend/currencyConverter/currency.js
  Frontend/currencyConverter/index.html
Labels: JWOC 2025, Medium

#608 Redesigned note app, added dark-mode, added custom scrollbar, fixed quiz dark mode
  Frontend/NotesAPP/notes.css
  Frontend/NotesAPP/notes.html
  Frontend/NotesAPP/notes.js
  Frontend/quiz/quiz.html
Labels: JWOC 2025, Hard

#606 Add the password generator project
  Frontend/currencyConverter/index.html
  Frontend/passwordGenerator/Coding Club-Projects and 3 more pages - Subhas - Microsoft​ Edge 05-03-2025 18_20_49.png
  Frontend/passwordGenerator/back.png
  Frontend/passwordGenerator/index.html
  Frontend/passwordGenerator/passApp.js
  Frontend/passwordGenerator/style.css
  Frontend/projectPage/projectpage.html
Labels: JWOC 2025, Hard

#528 select button added in the color picker
  Frontend/Calculator/calculator.js
  Frontend/ColorPicker/colorpicker.html
Labels: JWOC 2025, Medium

#549 Fixed the project page
  Frontend/.gitignore
  Frontend/drumKit/drumkit.html
  Frontend/projectPage/projectpage.html
Labels: JWOC 2025, Medium

#550 Word of the day and fav added
  Frontend/Dictionary/dictionary.html
Labels: JWOC 2025, Hard

#552 Scoreboard and timer added
  Frontend/guessing game/guessGame.html
Labels: JWOC 2025, Hard

#553 Added gradient generator
  Frontend/ColorPicker/colorpicker.html
Labels: JWOC 2025, Medium

#556 Toaster added in passweord gen
  Frontend/ColorPicker/colorpicker.html
  Frontend/Dictionary/dictionary.html
  Frontend/password generator/passgen.html
Labels: JWOC 2025, Hard

#557 History and thesarus added
  Frontend/Dictionary/dictionary.html
Labels: JWOC 2025, Hard

#561 darkmode added to the guessing game
  Frontend/guessing game/guessGame.html
  Frontend/password generator/passgen.html
Labels: JWOC 2025, Medium

#562 Profile btn fixed
  Frontend/Calculator/calculator.js
  Frontend/contributorPage/contributor.html
  Frontend/eventPage/event.html
  Frontend/index.html
  Frontend/projectPage/projectpage.html
  Frontend/reviewPage/review.html
Labels: JWOC 2025, Medium

#563 Darkmode added to the stopwatch
  Frontend/stopWatch/stopwatch.css
  Frontend/stopWatch/stopwatch.html
  Frontend/stopWatch/stopwatch.js
Labels: JWOC 2025, Medium

#564 darkmode for the typing speed
  Frontend/typingSpeed/typingSpeed.css
  Frontend/typingSpeed/typingSpeed.html
  Frontend/typingSpeed/typingSpeed.js
Labels: JWOC 2025, Hard

#618 Multilingual added
  Frontend/Calculator/calculator.js
  Frontend/Dictionary/dictionary.html
Labels: JWOC 2025, Hard

#619 faq fixed
  Frontend/mainPage/style.css
Labels: JWOC 2025, Medium

#612 Added custom scrollbar on resources page
  Frontend/resource/resource.css
  Frontend/resource/resource.html
Labels: JWOC 2025, Medium

#613 Fixed dark mode on blog page
  Frontend/blogPage/blog.css
  Frontend/blogPage/blog.html
Labels: JWOC 2025, Medium

#614 Fixed dark mode for all leaderboards
  Frontend/leaderboard/leaderboard.html
  Frontend/leaderboard/leaderboard1.html
  Frontend/leaderboard/leaderboard2.html
Labels: JWOC 2025, Medium

#653 Added New project BMI Calculator
  Frontend/Projects/Bmi Calculator/bmi.css
  Frontend/Projects/Bmi Calculator/bmi.html
  Frontend/Projects/Bmi Calculator/bmi.js
  Frontend/images/bmi.png
  Frontend/projectPage/projectpage.html
Labels: JWOC 2025, Hard

#655 Implemented new project guess the number game with custom scrollbar
  Frontend/Projects/Bmi Calculator/bmi.css
  Frontend/Projects/Guess the Number/guess.css
  Frontend/Projects/Guess the Number/guess.html
  Frontend/Projects/Guess the Number/guess.js
  Frontend/images/guess.png
  Frontend/projectPage/projectpage.html
Labels: JWOC 2025, Medium

#656 Implemented dark mode with back button on guess the number game
  Frontend/Projects/Guess the Number/guess.css
  Frontend/Projects/Guess the Number/guess.html
  Frontend/Projects/Guess the Number/guess.js
Labels: JWOC 2025, Hard

#695 Implemented dark mode with back button on memory card game
  Frontend/Projects/Memory Card Game/memory.css
  Frontend/Projects/Memory Card Game/memory.html
  Frontend/Projects/Memory Card Game/memory.js
Labels: JWOC 2025, Hard

#699 Added new project - pomodoro timer
  Frontend/Projects/Pomodoro Timer/pomodoro.css
  Frontend/Projects/Pomodoro Timer/pomodoro.html
  Frontend/Projects/Pomodoro Timer/pomodoro.js
  Frontend/images/pomodoro.png
  Frontend/projectPage/projectpage.html
Labels: JWOC 2025, Hard

#701 Added Dark mode, custom scrollbar and back button on pomodoro timer
  Frontend/Projects/Pomodoro Timer/pomodoro.css
  Frontend/Projects/Pomodoro Timer/pomodoro.html
  Frontend/Projects/Pomodoro Timer/pomodoro.js
Labels: JWOC 2025, Hard

#704 Added new project QR code generator with custom scrollbar
  Frontend/Projects/Qr Code Generator/qr.css
  Frontend/Projects/Qr Code Generator/qr.html
  Frontend/Projects/Qr Code Generator/qr.js
  Frontend/images/qr.png
  Frontend/projectPage/projectpage.html
Labels: JWOC 2025, Medium

#705 Added dark mode and back button on QR code generator
  Frontend/Projects/Qr Code Generator/qr.css
  Frontend/Projects/Qr Code Generator/qr.html
  Frontend/Projects/Qr Code Generator/qr.js
Labels: JWOC 2025, Hard

#706 Added New project - simon says game with custom scrollbar
  Frontend/Projects/Simon Says Game/simon.css
  Frontend/Projects/Simon Says Game/simon.html
  Frontend/Projects/Simon Says Game/simon.js
  Frontend/images/simon.png
  Frontend/projectPage/projectpage.html
Labels: JWOC 2025, Medium

#620 Added the edit profile fucntionality
  Frontend/Calculator/calculator.js
  Frontend/Dictionary/dictionary.html
  Frontend/User/edituser.html
  Frontend/User/user.html
Labels: JWOC 2025, Medium

#733 Fixed website responsiveness across various screen sizes
  Frontend/index.html
  Frontend/mainPage/style.css
Labels: JWOC 2025, Hard

#623 Saved password and toggle visibilty added
  Frontend/password generator/passgen.html
Labels: JWOC 2025, Medium

#624 gradient diraction maker and more gradient stops added
  Frontend/ColorPicker/colorpicker.html
Labels: JWOC 2025, Medium

#626 fav and gradient hsitory added
  Frontend/ColorPicker/colorpicker.html
Labels: JWOC 2025, Medium

#627 progress bar and temporary storage added
  Frontend/todo/todo.html
Labels: JWOC 2025, Hard

#628 Adedd voice input
  Frontend/todo/todo.html
Labels: JWOC 2025, Hard

#629 due dates and reminders added
  Frontend/todo/todo.html
Labels: JWOC 2025, Medium

#630 Adding categories and filter
  Frontend/todo/todo.html
Labels: JWOC 2025, Medium

#632 Retry and category added
  Frontend/guessing game/guessGame.html
Labels: JWOC 2025, Medium

#633 Progress bar and higlight red on worng ans and green on correct ans
  Frontend/quiz/quiz.html
Labels: JWOC 2025, Hard

#721 Added New Project tic tac toe
  Frontend/Projects/Simon Says Game/simon.css
  Frontend/Projects/Simon Says Game/simon.html
  Frontend/Projects/Simon Says Game/simon.js
  Frontend/Projects/Tic-Tac-Toe/tac.css
  Frontend/Projects/Tic-Tac-Toe/tac.html
  Frontend/Projects/Tic-Tac-Toe/tac.js
  Frontend/projectPage/project.css
  Frontend/projectPage/projectpage.html
  Frontend/public/images/bmi.png
  Frontend/public/images/codingclub.png
  Frontend/public/images/codingclub.svg
  Frontend/public/images/color.jpeg
  Frontend/public/images/download.jpg
  Frontend/public/images/download.png
  Frontend/public/images/github.png
  Frontend/public/images/guess.jpeg
  Frontend/public/images/guess.png
  Frontend/public/images/linkidn.png
  Frontend/public/images/memory.png
  Frontend/public/images/password.jpeg
  Frontend/public/images/pomodoro.png
  Frontend/public/images/qr.png
  Frontend/public/images/simon.png
  Frontend/public/images/tac.png
  Frontend/public/images/todo.jpeg
Labels: enhancement, JWOC 2025, Hard

#717 Added New project whack a mole
  Frontend/Projects/Bmi Calculator/bmi.css
  Frontend/Projects/Bmi Calculator/bmi.html
  Frontend/Projects/Bmi Calculator/bmi.js
  Frontend/Projects/Whack-a-Mole/mole.css
  Frontend/Projects/Whack-a-Mole/mole.html
  Frontend/Projects/Whack-a-Mole/mole.js
  Frontend/Projects/Whack-a-Mole/mole.png
  Frontend/images/whack.png
  Frontend/projectPage/projectpage.html
  Frontend/resource/resource.css
  Frontend/typingSpeed/typingSpeed.html
Labels: JWOC 2025, Hard

#764 Dark mode calculator
  Frontend/basicCalculator/basicCalculator.css
  Frontend/basicCalculator/basicCalculator.html
  Frontend/bubble_game/bubble.css
  Frontend/bubble_game/bubble.html
  Frontend/bubble_game/bubble.js
  Frontend/images/bubble_game.jpg
  Frontend/index.html
Labels: JWOC 2025, Hard

#763 Dark mode bubble game
  Frontend/bubble_game/bubble.css
  Frontend/bubble_game/bubble.html
  Frontend/bubble_game/bubble.js
Labels: JWOC 2025, Hard

#610 navbar,footer added in resource page
  Frontend/resource/resource.html
Labels: JWOC 2025, Hard

#611 Resource page scroll button added
  Frontend/resource/resource.html
Labels: JWOC 2025, Medium

#696 Resource page dark mode enhanced
  Frontend/resource/resource.css
Labels: JWOC 2025, Hard

#697 Leader page hover effect added in all pages
  Frontend/leaderboard/leaderboard.html
  Frontend/leaderboard/leaderboard1.html
  Frontend/leaderboard/leaderboard2.html
Labels: JWOC 2025, Medium

#698 Greeting card added in all leaderboard pages
  Frontend/leaderboard/leaderboard.html
  Frontend/leaderboard/leaderboard1.html
  Frontend/leaderboard/leaderboard2.html
Labels: JWOC 2025, Hard

#700 Svg logo added in place of png logo
  Frontend/blogPage/blog.html
  Frontend/contributorPage/contributor.html
  Frontend/index.html
  Frontend/projectPage/projectpage.html
  Frontend/resource/resource.html
  Frontend/reviewPage/review.html
Labels: JWOC 2025, Hard

#703 faq section toggle function resolved
  Frontend/eventPage/event.html
  Frontend/index.html
Labels: JWOC 2025, Medium

#747 Faq section search filter added
  Frontend/index.html
Labels: JWOC 2025, Medium

#748 Signup page footer links added
  Frontend/signupPage/signup.html
Labels: JWOC 2025, Medium

#555 added a pop up feature on newsletter subscribe (issue #351)
  Frontend/index.html
Labels: JWOC 2025, Medium

#751 why Choose us page redesigned
  Frontend/index.html
  Frontend/mainPage/style.css
  Frontend/projectPage/projectpage.html
Labels: JWOC 2025, Medium

#771 Project page all footer links added
  Frontend/projectPage/projectpage.html
Labels: JWOC 2025, Medium

#772 Privacy page logo fixed
  Frontend/privacyPage/privacy.css
  Frontend/termsPage/terms.css
Labels: JWOC 2025, Hard

#777 blog page responsiveness done
  Frontend/blogPage/blog.css
  Frontend/projectPage/projectpage.html
Labels: JWOC 2025, Hard

#780 project level option now visible in dark mode
  Frontend/index.html
  Frontend/mainPage/style.css
  Frontend/projectPage/projectpage.html
Labels: JWOC 2025, Medium

#784 Logo position fixed for project page
  Frontend/projectPage/projectpage.html
Labels: JWOC 2025, Medium

#765 Added back button on stop watch
  Frontend/stopWatch/stopwatch.css
  Frontend/stopWatch/stopwatch.html
Labels: JWOC 2025, Medium

#766 Fixed Navbar and projects in project page
  Frontend/projectPage/projectpage.html
Labels: JWOC 2025, Hard

#767 Fixed footer of project page
  Frontend/projectPage/projectpage.html
Labels: JWOC 2025, Medium

#768 Added Footer and custom scrollbar on all login pages
  Frontend/AllLoginPage/ailoginPage/ailogin.css
  Frontend/AllLoginPage/ailoginPage/ailogin.html
  Frontend/AllLoginPage/beginloginPage/beginlogin.css
  Frontend/AllLoginPage/beginloginPage/beginlogin.html
  Frontend/AllLoginPage/loginPage/login.css
  Frontend/AllLoginPage/loginPage/login.html
  Frontend/AllLoginPage/stackloginPage/stacklogin.css
  Frontend/AllLoginPage/stackloginPage/stacklogin.html
Labels: JWOC 2025, Hard

#774 Fixed working of Add event button and submit button
  Frontend/index.html
Labels: JWOC 2025, Medium

#776 Fixed Alignment of project search bar
  Frontend/mainPage/style.css
  Frontend/projectPage/project.css
Labels: JWOC 2025, Medium

#778 Fixed all back button for correct redirection
  Frontend/AllLoginPage/ailoginPage/ailogin.html
  Frontend/AllLoginPage/beginloginPage/beginlogin.html
  Frontend/AllLoginPage/loginPage/login.html
  Frontend/AllLoginPage/stackloginPage/stacklogin.html
  Frontend/Calculator/calculator.html
  Frontend/User/user.html
  Frontend/quiz/quiz.html
  Frontend/signupPage/signup.html
Labels: JWOC 2025, Medium

#779 Designed contributor's view profile button
  Frontend/contributorPage/contributor.css
Labels: JWOC 2025, Hard

#781 Fixed links of footer in contributors page
  Frontend/contributorPage/contributor.html
Labels: JWOC 2025, Medium

#782 Fixed dark mode and functions in Expense Tracker
  Frontend/ExpenseTracker/expenseTracker.html
  Frontend/ExpenseTracker/expenseTracker.js
  Frontend/ExpenseTracker/expensetracker.css
Labels: JWOC 2025, Hard

#783 Fixed images of project page
  Frontend/projectPage/projectpage.html
Labels: JWOC 2025, Medium

#828 Added new project age calculator
  Frontend/Projects/Age Calculator/age.css
  Frontend/Projects/Age Calculator/age.html
  Frontend/Projects/Age Calculator/age.js
  Frontend/images/age.png
  Frontend/projectPage/projectpage.html
Labels: JWOC 2025, Hard

#829 Added New project Quotes Generator
  Frontend/Projects/Quotes Generator/quotes.css
  Frontend/Projects/Quotes Generator/quotes.html
  Frontend/Projects/Quotes Generator/quotes.js
  Frontend/images/quotes.png
  Frontend/projectPage/projectpage.html
Labels: JWOC 2025, Hard

#830 Added New project Hangman Game
  Frontend/Projects/Hangman Game/hangman.css
  Frontend/Projects/Hangman Game/hangman.html
  Frontend/Projects/Hangman Game/hangman.js
  Frontend/images/hangman.png
  Frontend/projectPage/projectpage.html
Labels: JWOC 2025, Hard

#831 Added New project URL Shortener
  Frontend/Projects/URL Shortener/url.css
  Frontend/Projects/URL Shortener/url.html
  Frontend/Projects/URL Shortener/url.js
  Frontend/images/url.png
  Frontend/projectPage/projectpage.html
Labels: JWOC 2025, Hard

#833 Added New project Flippy Bird
  Frontend/Projects/Flappy Bird/flappy.css
  Frontend/Projects/Flappy Bird/flappy.html
  Frontend/Projects/Flappy Bird/flappy.js
  Frontend/images/flippy.png
  Frontend/projectPage/projectpage.html
Labels: JWOC 2025, Hard

#845 Implemented dark mode, back button and custom scrollbar on age calculator
  Frontend/Projects/Age Calculator/age.css
  Frontend/Projects/Age Calculator/age.html
  Frontend/Projects/Age Calculator/age.js
Labels: JWOC 2025, Medium

#846 Implemented dark mode, back button and custom scrollbar on quotes generator
  Frontend/Projects/Quotes Generator/quotes.css
  Frontend/Projects/Quotes Generator/quotes.html
  Frontend/Projects/Quotes Generator/quotes.js
Labels: JWOC 2025, Medium

#848 Implemented dark mode, back button and custom scrollbar on url shortener
  Frontend/Projects/URL Shortener/url.css
  Frontend/Projects/URL Shortener/url.html
  Frontend/Projects/URL Shortener/url.js
Labels: JWOC 2025, Medium

#849 Implemented dark mode, back button on flippy game
  Frontend/Projects/Flappy Bird/flappy.css
  Frontend/Projects/Flappy Bird/flappy.html
  Frontend/Projects/Flappy Bird/flappy.js
Labels: JWOC 2025, Medium

#850 fixed overflow in typing speed
  Frontend/typingSpeed/typingSpeed.css
Labels: JWOC 2025, Medium

#851 fixed profile link in event page
  Frontend/eventPage/event.html
Labels: JWOC 2025, Easy

#852 fixed profile link in all page
  Frontend/contributorPage/contributor.html
  Frontend/resource/resource.html
  Frontend/reviewPage/review.html
Labels: JWOC 2025, Easy

#789 Virtual pet simulator added
  Frontend/projectV2/petSim/index.html
Labels: JWOC 2025, Hard

#790 2048 game added
  Frontend/projectV2/2048/index.html
Labels: JWOC 2025, Hard

#876 Fixed Dark mode for contact page
  Frontend/index.html
  Frontend/mainPage/style.css
Labels: JWOC 2025, Medium

#877 Fixed links of resources page
  Frontend/resource/resource.html
Labels: JWOC 2025, Medium

#878 Fixed Project page ui
  Frontend/projectPage/projectpage.html
Labels: JWOC 2025, Hard

#879 Redesigned Typing speed
  Frontend/typingSpeed/typingSpeed.css
  Frontend/typingSpeed/typingSpeed.html
  Frontend/typingSpeed/typingSpeed.js
Labels: JWOC 2025, Medium

#895 Added dark mode and back button on ai chatbot
  Frontend/Projects/AI Chatbot/ai.css
  Frontend/Projects/AI Chatbot/ai.html
  Frontend/Projects/AI Chatbot/ai.js
Labels: JWOC 2025, Medium

#896 Added New Project snake game
  Frontend/Projects/Snake Game/snake.css
  Frontend/Projects/Snake Game/snake.html
  Frontend/Projects/Snake Game/snake.js
  Frontend/images/snake.png
  Frontend/projectPage/projectpage.html
Labels: JWOC 2025, Hard

#898 Added New Project Space Shooter game
  Frontend/Projects/Space Shooter Game/space.css
  Frontend/Projects/Space Shooter Game/space.html
  Frontend/Projects/Space Shooter Game/space.js
  Frontend/images/space.png
  Frontend/projectPage/projectpage.html
Labels: JWOC 2025, Hard

#899 Added New Project Platformer game
  Frontend/Projects/Platformer Game/platformer.css
  Frontend/Projects/Platformer Game/platformer.html
  Frontend/Projects/Platformer Game/platformer.js
  Frontend/images/platformer.png
  Frontend/projectPage/projectpage.html
Labels: JWOC 2025, Hard

#900 Added New Project Pong game
  Frontend/Projects/Pong Game/pong.css
  Frontend/Projects/Pong Game/pong.html
  Frontend/Projects/Pong Game/pong.js
  Frontend/images/pong.png
  Frontend/projectPage/projectpage.html
Labels: JWOC 2025, Hard

#901 Added Dark mode and back button on pong game
  Frontend/Projects/Pong Game/pong.css
  Frontend/Projects/Pong Game/pong.html
  Frontend/Projects/Pong Game/pong.js
Labels: JWOC 2025, Medium

#902 Added Dark mode and back button on snake game
  Frontend/Projects/Pong Game/pong.css
  Frontend/Projects/Snake Game/snake.css
  Frontend/Projects/Snake Game/snake.html
  Frontend/Projects/Snake Game/snake.js
Labels: JWOC 2025, Medium

#903 Added Dark mode and back button on breakout game
  Frontend/Projects/Breakout Game/breakout.css
  Frontend/Projects/Breakout Game/breakout.html
  Frontend/Projects/Breakout Game/breakout.js
Labels: JWOC 2025, Medium

#904 Added Dark mode and back button on space shooter game
  Frontend/Projects/Space Shooter Game/space.css
  Frontend/Projects/Space Shooter Game/space.html
  Frontend/Projects/Space Shooter Game/space.js
Labels: JWOC 2025, Medium

#906 Redesigned 2048 game
  Frontend/projectV2/2048/index.html
Labels: JWOC 2025, Hard

#907 Added 2048 game in more project page
  Frontend/images/2048.png
  Frontend/projectPage/projectpage.html
Labels: JWOC 2025, Hard

#908 Added Virtual Pet Simulator in more project page
  Frontend/images/petsim.png
  Frontend/projectPage/projectpage.html
Labels: JWOC 2025, Hard
